---
# See https://github.com/actions/virtual-environments

name: Test Code on OS/X
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-11
        perl: ['5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied ExtUtils::MakeMaker
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes
          cpanm -iqn --skip-satisfied Test::Portability::Files Test::Carp
          cpanm -iqn --skip-satisfied Test::Pod::Coverage Test::Most
          cpanm -iqn --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: |
          cover -test
          cover -report codecov
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -t fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
        shell: bash
        env:
          AUTHOR_TESTING: 1
          CODECOV_TOKEN: fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
