---
# See https://github.com/actions/virtual-environments

name: Test Code on Windows
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-2019
        perl: ['5.34', '5.32', '5.30', '5.28']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied ExtUtils::MakeMaker
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Carp Test::Pod::Coverage Test::Most
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: |
          choco --no-progress install codecov
          cover -test
          cover -report codecov
          curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
          ./codecov.exe -t fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
        env:
          AUTHOR_TESTING: 1
          CODECOV_TOKEN: fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
